# This is a basic workflow to help you get started with Actions

name: pr-title-to-label

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "label"
  labelit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          path: repo
          
      - uses: actions/checkout@v2
        with:
          repository: jparkerweb/pr-title-to-label
          # ref: main
          # token: ${{ secrets.NAME_OF_ACCESS_TOKEN_IF_PRIVATE_REPO }}
          path: pr-title-to-label
          
      - id: install
        run: cd $GITHUB_WORKSPACE/pr-title-to-label && npm install

      - id: label-the-pr
        run: cd $GITHUB_WORKSPACE/pr-title-to-label && node app.js
